### ISSUE TITLE
Concurrent Staged Data

### ISSUE THREAD

**Issue by di-wu** [DepartureLabsIC/non-fungible-token#24]
You can only stage write for one NFT (and one asset) at a time.

https://github.com/DepartureLabsIC/non-fungible-token/blob/4ca7540c3397af9198edab71742c44f118d6f9cc/src/token.mo#L107

https://github.com/DepartureLabsIC/non-fungible-token/blob/4ca7540c3397af9198edab71742c44f118d6f9cc/src/static.mo#L43

Sidenote: you need to be a contract owner to stage data.

---

How would we enable concurrent staging?

**Comment by SuddenlyHazel** [comment]
Great call out 

Here is what I'm thinking 

```
 // new type
 public type StagedWrite = {
        #Init : {
            type : {#NFT; #Asset : Text}; // asset text is the path. IF NFT, increment tokenId?
            size     : Nat; 
            callback : ?Callback
        };
        #Chunk : {
            type : {#NFT : Text; #Asset : Text}; // nft text is the tokenid; asset text is the path
            chunk    : Blob; 
            callback : ?Callback
        };
    };
```

Handling concurrent assets seems straight forward, but NFTs not so much since we use the built in token counter. In the event of #Init with a type #NFT should we just increment the token counter and attach the token id on a new Callback record? What do you think?

Last thought, we might want to put some thought into exposing some helper APIs around purging staged state, checking the current staged state, etc.
